/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QrRouteImport } from './routes/qr'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as FloorRouteImport } from './routes/floor'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugTableTokenRouteImport } from './routes/t.$slug.$tableToken'

const QrRoute = QrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorRoute = FloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugTableTokenRoute = TSlugTableTokenRouteImport.update({
  id: '/t/$slug/$tableToken',
  path: '/t/$slug/$tableToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/demo': typeof DemoRoute
  '/floor': typeof FloorRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/qr': typeof QrRoute
  '/t/$slug/$tableToken': typeof TSlugTableTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/demo': typeof DemoRoute
  '/floor': typeof FloorRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/qr': typeof QrRoute
  '/t/$slug/$tableToken': typeof TSlugTableTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/demo': typeof DemoRoute
  '/floor': typeof FloorRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/qr': typeof QrRoute
  '/t/$slug/$tableToken': typeof TSlugTableTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/demo'
    | '/floor'
    | '/kitchen'
    | '/menu'
    | '/qr'
    | '/t/$slug/$tableToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/demo'
    | '/floor'
    | '/kitchen'
    | '/menu'
    | '/qr'
    | '/t/$slug/$tableToken'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/demo'
    | '/floor'
    | '/kitchen'
    | '/menu'
    | '/qr'
    | '/t/$slug/$tableToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DemoRoute: typeof DemoRoute
  FloorRoute: typeof FloorRoute
  KitchenRoute: typeof KitchenRoute
  MenuRoute: typeof MenuRoute
  QrRoute: typeof QrRoute
  TSlugTableTokenRoute: typeof TSlugTableTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/qr': {
      id: '/qr'
      path: '/qr'
      fullPath: '/qr'
      preLoaderRoute: typeof QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor': {
      id: '/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof FloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/$tableToken': {
      id: '/t/$slug/$tableToken'
      path: '/t/$slug/$tableToken'
      fullPath: '/t/$slug/$tableToken'
      preLoaderRoute: typeof TSlugTableTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DemoRoute: DemoRoute,
  FloorRoute: FloorRoute,
  KitchenRoute: KitchenRoute,
  MenuRoute: MenuRoute,
  QrRoute: QrRoute,
  TSlugTableTokenRoute: TSlugTableTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
